spring.application.name=auth-service

spring.datasource.url=jdbc:mysql://localhost:3306/auth-jwt?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456789

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create  
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
server.address=0.0.0.0
//Define tu propio puerto
server.port=8080
